### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by rminderhoud** [dev-osrose/osIROSE-new#99]
Can't build current trunk (3e2ff1a125cd1a33e5f1ebc2ff549935d8bcc216).

```
make[2]: *** No rule to make target '../src/proto/PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND', needed by 'generated/iscpackets.pb.cc'.  Stop.
CMakeFiles/Makefile2:191: recipe for target 'src/proto/CMakeFiles/protoGen.dir/all' failed
make[1]: *** [src/proto/CMakeFiles/protoGen.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

Steps:
1. Clone master
2. Execute `./unix_env_setup.sh`
3. `cd build/`
4. `make`

**Comment by L3nn0x** [comment]
That's a known problem that should be resolved in the cmake_revamp branch. Try that branch and tell us if it works :)

**Comment by rminderhoud** [comment]
Unfortunately i still get the same build error.

```
make[2]: *** No rule to make target '../src/proto/PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND', needed by 'generated/iscpackets.pb.cc'.  Stop.
CMakeFiles/Makefile2:291: recipe for target 'src/proto/CMakeFiles/protoGen.dir/all' failed
make[1]: *** [src/proto/CMakeFiles/protoGen.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

Steps:
1. `git checkout cmake_revamp`
2. `./unix_env_setup.sh`
3. `cd build`
4. `make`

**Comment by L3nn0x** [comment]
Do you have the `protobuf` directory in `~/` with binaries in it? If not, do:

```cd $OSIROSE_ROOT/3rdParty/protobuf
./autogen.sh
./configure --prefix=$HOME/protobuf
make -j4 && make install
```

Then try again and tell me if it works.

**Comment by rminderhoud** [comment]
Couldn't install it in my home directory `ibtool:   error: error: cannot install 'libprotoc.la' to a directory not ending in /usr/local/lib`

Installed it the default location instead. Still get the error (ran `make clean && make`).

**Comment by RavenX8** [comment]
What os are you running? Also on the cmake_revamp branch I haven't updated the script to the new way of installing everything yet. I'll do that in a few minutes when I can take a look.

**Comment by rminderhoud** [comment]
```
$ uname -ra
Linux Ralph-Ubuntu 4.10.0-22-generic #24-Ubuntu SMP Mon May 22 17:43:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=17.04
DISTRIB_CODENAME=zesty
DISTRIB_DESCRIPTION="Ubuntu 17.04"
```

**Comment by RavenX8** [comment]
can you try running the script in 2a689b241f8b2827bf10af36ab1a0c6319674211? That one should just work now.

I'm currently testing it with a brand new fresh install of ubuntu trusty. I'll test it with a new install of zesty when I get home later today.

**Comment by rminderhoud** [comment]
Looks like it's getting close. I think the issue is on this line but I'm not certain: https://github.com/dev-osrose/osIROSE-new/blob/trunk/ci/install-protobuf.sh#L14

When running the new script I get this error when building dependencies:

```
libtool:   error: error: cannot install 'libprotoc.la' to a directory not ending in /usr/local/lib
akefile:2039: recipe for target 'install-libLTLIBRARIES' failed
make[3]: *** [install-libLTLIBRARIES] Error 1
make[3]: Leaving directory '/mnt/blue/rose/osIROSE-new/3rdparty/protobuf/src'
Makefile:7648: recipe for target 'install-am' failed
make[2]: *** [install-am] Error 2
make[2]: Leaving directory '/mnt/blue/rose/osIROSE-new/3rdparty/protobuf/src'
Makefile:7642: recipe for target 'install' failed
make[1]: *** [install] Error 2
make[1]: Leaving directory '/mnt/blue/rose/osIROSE-new/3rdparty/protobuf/src'
Makefile:1325: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
```

Which ends up with this error when finally running make for the server bins:

```
[ 26%] Running C++ protocol buffer compiler on /mnt/blue/rose/osIROSE-new/src/proto/iscpackets.proto with root /mnt/blue/rose/osIROSE-new/src/proto, generating: /mnt/blue/rose/osIROSE-new/build/generated/iscpackets.pb.cc
/usr/local/bin/protoc: error while loading shared libraries: libprotoc.so.11: cannot open shared object file: No such file or directory
```

**Edit** Interestingly the protobuf binary gets installed to `/usr/local/bin` but the libs are in `~/protobuf/lib` and `libprotoc.so.11` is missing. 

**Edit2** `libprotoc.so.11` is in `/usr/local/lib` so either my system is not configured correctly (other libs work?) or `/usr/local/lib` not being checked?

**Fixed** Fixed it by running `ldconfig` -- maybe `/usr/local/lib` should be exported in build script? `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib`

**Comment by L3nn0x** [comment]
That's because the script tries to install everything in `~/protobuf`, to keep the host as clean as possible. Not sure why it doesn't do as planned in your case though.

**Comment by RavenX8** [comment]
The system installs all of the external libs into the 3rdparty folder. I've never seen the issue where it would throw an error about not allowing an install anywhere else but /usr/local/lib.

Edit: The ~/protobuf directory you have is from running the script that was in master/trunk. Those haven't been updated yet with the new install path.

**Comment by RavenX8** [comment]
Just updated the install-protobuf script. Try it now. It seems that libtool sometimes leaves files it shouldn't in the workspace so doing a make clean right after configure usually fixes the issue with the install path.

**Comment by rminderhoud** [comment]
Looks like the libs are installing in the intended place `3rdparty/lib` but it still fails for `libprotoc.la`. So technically the protobuf build fails because it can't install that last library but the other libs make it into the directory before it fails:

```
libtool: install: /usr/bin/install -c .libs/libprotobuf-lite.so.11.0.0 /mnt/blue/rose/osIROSE-new/3rdparty/lib/libprotobuf-lite.so.11.0.0
libtool: install: (cd /mnt/blue/rose/osIROSE-new/3rdparty/lib && { ln -s -f libprotobuf-lite.so.11.0.0 libprotobuf-lite.so.11 || { rm -f libprotobuf-lite.so.11 && ln -s libprotobuf-lite.so.11.0.0 libprotobuf-lite.so.11; }; })
libtool: install: (cd /mnt/blue/rose/osIROSE-new/3rdparty/lib && { ln -s -f libprotobuf-lite.so.11.0.0 libprotobuf-lite.so || { rm -f libprotobuf-lite.so && ln -s libprotobuf-lite.so.11.0.0 libprotobuf-lite.so; }; })
libtool: install: /usr/bin/install -c .libs/libprotobuf-lite.lai /mnt/blue/rose/osIROSE-new/3rdparty/lib/libprotobuf-lite.la
libtool: install: /usr/bin/install -c .libs/libprotobuf.so.11.0.0 /mnt/blue/rose/osIROSE-new/3rdparty/lib/libprotobuf.so.11.0.0
libtool: install: (cd /mnt/blue/rose/osIROSE-new/3rdparty/lib && { ln -s -f libprotobuf.so.11.0.0 libprotobuf.so.11 || { rm -f libprotobuf.so.11 && ln -s libprotobuf.so.11.0.0 libprotobuf.so.11; }; })
libtool: install: (cd /mnt/blue/rose/osIROSE-new/3rdparty/lib && { ln -s -f libprotobuf.so.11.0.0 libprotobuf.so || { rm -f libprotobuf.so && ln -s libprotobuf.so.11.0.0 libprotobuf.so; }; })
libtool: install: /usr/bin/install -c .libs/libprotobuf.lai /mnt/blue/rose/osIROSE-new/3rdparty/lib/libprotobuf.la
libtool:   error: error: cannot install 'libprotoc.la' to a directory not ending in /usr/local/lib
```

I haven't dug into that script but I think it also doesn't install the `protoc` binary because it's not in `3rdparty/bin` and I get the error:

`make[2]: *** No rule to make target '../src/proto/PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND', needed by 'generated/iscpackets.pb.cc'.  Stop.`

when trying to run the make file in `build/`

**Comment by RavenX8** [comment]
we may have to move away from protobuf. 

You could remove the --prefix from configure and install it normally. The --prefix is there to keep the whole project self-contained that way if you needed to you could just delete the repo folder and it would remove everything. 

Also please delete the build directory in your project folder and rerun cmake to regenerate the files.

```
mkdir build
cd build
CC=gcc-6 CXX=g++-6 cmake -DENABLE_TESTING=ON -DENABLE_TESTING_COVERAGE=OFF ..

**Comment by rminderhoud** [comment]
Fixed with Raven's latest commit:  c330e31
